package jp.co.paypaycard.screening.creditcommon.entity.db;

import lombok.Data;

/**
 * H48(DocBell電話接続状況履歴情報)テーブルのエンティティクラス
 */
@Data
public class H48Entity {
    /** 申込番号 */
    private String H48_MOSHIKOMI_NO;
    /** 区分 */
    private String H48_KBN;
    /** 直近・調査日付 */
    private String H48_SRC_DATE;
    /** 直近・ステータス */
    private String H48_STATUS;
    /** 直近・移転先電話番号 */
    private String H48_TEL_NEW;
    /** 直近・履歴数 */
    private String H48_RIREKI;
    /** 履歴１・調査日付 */
    private String H48_SRC_DATE1;
    /** 履歴１・ステータス */
    private String H48_STATUS1;
    /** 履歴１・移転先電話番号 */
    private String H48_TEL_NEW1;
    /** 履歴２・調査日付 */
    private String H48_SRC_DATE2;
    /** 履歴２・ステータス */
    private String H48_STATUS2;
    /** 履歴２・移転先電話番号 */
    private String H48_TEL_NEW2;
    /** 履歴３・調査日付 */
    private String H48_SRC_DATE3;
    /** 履歴３・ステータス */
    private String H48_STATUS3;
    /** 履歴３・移転先電話番号 */
    private String H48_TEL_NEW3;
    /** 履歴４・調査日付 */
    private String H48_SRC_DATE4;
    /** 履歴４・ステータス */
    private String H48_STATUS4;
    /** 履歴４・移転先電話番号 */
    private String H48_TEL_NEW4;
    /** 履歴５・調査日付 */
    private String H48_SRC_DATE5;
    /** 履歴５・ステータス */
    private String H48_STATUS5;
    /** 履歴５・移転先電話番号 */
    private String H48_TEL_NEW5;
    /** 履歴６・調査日付 */
    private String H48_SRC_DATE6;
    /** 履歴６・ステータス */
    private String H48_STATUS6;
    /** 履歴６・移転先電話番号 */
    private String H48_TEL_NEW6;
    /** 履歴７・調査日付 */
    private String H48_SRC_DATE7;
    /** 履歴７・ステータス */
    private String H48_STATUS7;
    /** 履歴７・移転先電話番号 */
    private String H48_TEL_NEW7;
    /** 履歴８・調査日付 */
    private String H48_SRC_DATE8;
    /** 履歴８・ステータス */
    private String H48_STATUS8;
    /** 履歴８・移転先電話番号 */
    private String H48_TEL_NEW8;
    /** 履歴９・調査日付 */
    private String H48_SRC_DATE9;
    /** 履歴９・ステータス */
    private String H48_STATUS9;
    /** 履歴９・移転先電話番号 */
    private String H48_TEL_NEW9;
    /** 履歴１０・調査日付 */
    private String H48_SRC_DATE10;
    /** 履歴１０・ステータス */
    private String H48_STATUS10;
    /** 履歴１０・移転先電話番号 */
    private String H48_TEL_NEW10;
    /** 履歴１１・調査日付 */
    private String H48_SRC_DATE11;
    /** 履歴１１・ステータス */
    private String H48_STATUS11;
    /** 履歴１１・移転先電話番号 */
    private String H48_TEL_NEW11;
    /** 履歴１２・調査日付 */
    private String H48_SRC_DATE12;
    /** 履歴１２・ステータス */
    private String H48_STATUS12;
    /** 履歴１２・移転先電話番号 */
    private String H48_TEL_NEW12;
    /** 履歴１３・調査日付 */
    private String H48_SRC_DATE13;
    /** 履歴１３・ステータス */
    private String H48_STATUS13;
    /** 履歴１３・移転先電話番号 */
    private String H48_TEL_NEW13;
    /** 履歴１４・調査日付 */
    private String H48_SRC_DATE14;
    /** 履歴１４・ステータス */
    private String H48_STATUS14;
    /** 履歴１４・移転先電話番号 */
    private String H48_TEL_NEW14;
    /** 履歴１５・調査日付 */
    private String H48_SRC_DATE15;
    /** 履歴１５・ステータス */
    private String H48_STATUS15;
    /** 履歴１５・移転先電話番号 */
    private String H48_TEL_NEW15;
    /** 履歴１６・調査日付 */
    private String H48_SRC_DATE16;
    /** 履歴１６・ステータス */
    private String H48_STATUS16;
    /** 履歴１６・移転先電話番号 */
    private String H48_TEL_NEW16;
    /** 履歴１７・調査日付 */
    private String H48_SRC_DATE17;
    /** 履歴１７・ステータス */
    private String H48_STATUS17;
    /** 履歴１７・移転先電話番号 */
    private String H48_TEL_NEW17;
    /** 履歴１８・調査日付 */
    private String H48_SRC_DATE18;
    /** 履歴１８・ステータス */
    private String H48_STATUS18;
    /** 履歴１８・移転先電話番号 */
    private String H48_TEL_NEW18;
    /** 履歴１９・調査日付 */
    private String H48_SRC_DATE19;
    /** 履歴１９・ステータス */
    private String H48_STATUS19;
    /** 履歴１９・移転先電話番号 */
    private String H48_TEL_NEW19;
    /** 履歴２０・調査日付 */
    private String H48_SRC_DATE20;
    /** 履歴２０・ステータス */
    private String H48_STATUS20;
    /** 履歴２０・移転先電話番号 */
    private String H48_TEL_NEW20;
    /** 変換１・調査年月 */
    private String H48_CONV_SRC_DATE1;
    /** 変換１・ステータス */
    private String H48_CONV_STATUS1;
    /** 変換１・移転先電話番号 */
    private String H48_CONV_TEL_NEW1;
    /** 変換２・調査年月 */
    private String H48_CONV_SRC_DATE2;
    /** 変換２・ステータス */
    private String H48_CONV_STATUS2;
    /** 変換２・移転先電話番号 */
    private String H48_CONV_TEL_NEW2;
    /** 変換３・調査年月 */
    private String H48_CONV_SRC_DATE3;
    /** 変換３・ステータス */
    private String H48_CONV_STATUS3;
    /** 変換３・移転先電話番号 */
    private String H48_CONV_TEL_NEW3;
    /** 変換４・調査年月 */
    private String H48_CONV_SRC_DATE4;
    /** 変換４・ステータス */
    private String H48_CONV_STATUS4;
    /** 変換４・移転先電話番号 */
    private String H48_CONV_TEL_NEW4;
    /** 変換５・調査年月 */
    private String H48_CONV_SRC_DATE5;
    /** 変換５・ステータス */
    private String H48_CONV_STATUS5;
    /** 変換５・移転先電話番号 */
    private String H48_CONV_TEL_NEW5;
    /** 変換６・調査年月 */
    private String H48_CONV_SRC_DATE6;
    /** 変換６・ステータス */
    private String H48_CONV_STATUS6;
    /** 変換６・移転先電話番号 */
    private String H48_CONV_TEL_NEW6;
    /** 変換７・調査年月 */
    private String H48_CONV_SRC_DATE7;
    /** 変換７・ステータス */
    private String H48_CONV_STATUS7;
    /** 変換７・移転先電話番号 */
    private String H48_CONV_TEL_NEW7;
    /** 変換８・調査年月 */
    private String H48_CONV_SRC_DATE8;
    /** 変換８・ステータス */
    private String H48_CONV_STATUS8;
    /** 変換８・移転先電話番号 */
    private String H48_CONV_TEL_NEW8;
    /** 変換９・調査年月 */
    private String H48_CONV_SRC_DATE9;
    /** 変換９・ステータス */
    private String H48_CONV_STATUS9;
    /** 変換９・移転先電話番号 */
    private String H48_CONV_TEL_NEW9;
    /** 変換１０・調査年月 */
    private String H48_CONV_SRC_DATE10;
    /** 変換１０・ステータス */
    private String H48_CONV_STATUS10;
    /** 変換１０・移転先電話番号 */
    private String H48_CONV_TEL_NEW10;
    /** 変換１１・調査年月 */
    private String H48_CONV_SRC_DATE11;
    /** 変換１１・ステータス */
    private String H48_CONV_STATUS11;
    /** 変換１１・移転先電話番号 */
    private String H48_CONV_TEL_NEW11;
    /** 変換１２・調査年月 */
    private String H48_CONV_SRC_DATE12;
    /** 変換１２・ステータス */
    private String H48_CONV_STATUS12;
    /** 変換１２・移転先電話番号 */
    private String H48_CONV_TEL_NEW12;
}